<?
$aMenuLinks = Array(
	Array(
		"каталог", 
		"/catalog/", 
		Array(), 
		Array("image"=>"/images/basket.gif"), 
		"" 
	),
	Array(
		"новости", 
		"/news/index.php", 
		Array(), 
		Array("image"=>"/images/price.gif"), 
		"" 
	),
	Array(
		"статьи", 
		"/articles/", 
		Array(), 
		Array("image"=>"/images/price.gif"), 
		"" 
	),
	Array(
		"о компании", 
		"/about/", 
		Array(), 
		Array("image"=>"/images/o_com.gif"), 
		"" 
	),
	Array(
		"партнеры", 
		"/partners/", 
		Array(), 
		Array("image"=>"/images/dealer.gif"), 
		"" 
	),
	Array(
		"контакты", 
		"/contacts/", 
		Array(), 
		Array("image"=>"/images/contacts.gif"), 
		"" 
	),
	Array(
		"сервис", 
		"/service/", 
		Array(), 
		Array("image"=>"/images/serv.gif"), 
		"" 
	)
);
?>